name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy files via SFTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cluster121.hosting.ovh.net
          username: runvatv
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: sftp
          port: 22
          server-dir: /www/